
services:
  freeipa-server:
    image: freeipa/freeipa-server:centos-9-stream
    restart: unless-stopped
    hostname: ec2-65-0-150-75.ap-south-1.compute.amazonaws.com
    container_name: freeipa-server
    environment:
      IPA_SERVER_IP: 65.0.150.75
      IPA_SERVER_HOSTNAME: ec2-65-0-150-75.ap-south-1.compute.amazonaws.com
    tty: true
    stdin_open: true
    privileged: true
    pid: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - freeipa-data:/data
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    command:
      - -U
      - --domain=ec2-65-0-150-75.ap-south-1.compute.amazonaws.com
      - --realm=EC2-65-0-150-75.AP-SOUTH-1.COMPUTE.AMAZONAWS.COM
      - --http-pin=Admin@123
      - --dirsrv-pin=Admin@123
      - --ds-password=Admin@123
      - --admin-password=Admin@123
      - --no-host-dns
      - --unattended
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
      - "123:123/udp"
      - "7389:7389"
      - "9443:9443"
      - "9444:9444"
      - "9445:9445"
volumes:
  freeipa-data: