services:
  freeipa-server:
    image: freeipa/freeipa-server:rocky-9
    container_name: freeipa-server
    hostname: ec2-65-0-150-75.ap-south-1.compute.amazonaws.com
    privileged: true                # solves systemd/cgroup issues
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    environment:
      IPA_SERVER_IP: "65.0.150.75"
      IPA_SERVER_HOSTNAME: "ec2-65-0-150-75.ap-south-1.compute.amazonaws.com"
      PASSWORD: "Admin@123"
    tty: true
    stdin_open: true
    volumes:
      - freeipa-data:/data:Z
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
    restart: unless-stopped

volumes:
  freeipa-data:
